In [1]:
#Simple 2 layer Neural Network to predict output of a XOR logic gate
#An Exclusive Or f(ie. XOR) unction returns a 1 only if all the inputs are either 0 or 1
#https://www.dummies.com/programming/python/how-to-build-a-simple-neural-network-in-python/

# 2 Layer Neural Network in NumPy
import numpy as np

# X = input of our 3 input XOR gate
# set up the inputs of the neural network (right from the table)
X = np.array(([0,0,0],[0,0,1],[0,1,0], \
[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]), dtype=float)

# y = our output of our neural network
y = np.array(([1], [0], [0], [0], [0], \
[0], [0], [1]), dtype=float)

# what value we want to predict
xPredicted = np.array(([0,0,1]), dtype=float)
X = X/np.amax(X, axis=0) # maximum of X input array

# maximum of xPredicted (our input data for the prediction)
xPredicted = xPredicted/np.amax(xPredicted, axis=0)

# set up our Loss file for graphing
lossFile = open("SumSquaredLossList.csv", "w")
class Neural_Network (object):
    def __init__(self): #parameters
        self.inputLayerSize = 3 # X1,X2,X3
        self.outputLayerSize = 1 # Y1
        self.hiddenLayerSize = 4 # Size of the hidden layer
        # build weights of each layer
        # set to random values
        # look at the interconnection diagram to make sense of this
        # 3x4 matrix for input to hidden
        self.W1 = \
        np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        
        # 4x1 matrix for hidden layer to output
        self.W2 = \
        np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def feedForward(self, X):
        # feedForward propagation through our network
        # dot product of X (input) and first set of 3x4 weights
        self.z = np.dot(X, self.W1)
        # the activationSigmoid activation function - neural magic
        self.z2 = self.activationSigmoid(self.z)
        # dot product of hidden layer (z2) and second set of 4x1 weights
        self.z3 = np.dot(self.z2, self.W2)
        # final activation function - more neural magic
        o = self.activationSigmoid(self.z3)
        return o
    
    def backwardPropagate(self, X, y, o):
        # backward propagate through the network
        # calculate the error in output
        self.o_error = y - o
        # apply derivative of activationSigmoid to error
        self.o_delta = self.o_error*self.activationSigmoidPrime(o)
        # z2 error: how much our hidden layer weights contributed to output
        # error
        self.z2_error = self.o_delta.dot(self.W2.T)
        # applying derivative of activationSigmoid to z2 error
        self.z2_delta = self.z2_error*self.activationSigmoidPrime(self.z2)
        # adjusting first set (inputLayer --> hiddenLayer) weights
        self.W1 += X.T.dot(self.z2_delta)
        # adjusting second set (hiddenLayer --> outputLayer) weights
        self.W2 += self.z2.T.dot(self.o_delta)
        
    def trainNetwork(self, X, y):
        # feed forward the loop
        o = self.feedForward(X)
        # and then back propagate the values (feedback)
        self.backwardPropagate(X, y, o)

    def activationSigmoid(self, s):
        # activation function
        # simple activationSigmoid curve as in the book
        return 1/(1+np.exp(-s))

    def activationSigmoidPrime(self, s):
        # First derivative of activationSigmoid
        # calculus time!
        return s * (1 - s)

    def saveSumSquaredLossList(self,i,error):
        lossFile.write(str(i)+","+str(error.tolist())+'\n')

    def saveWeights(self):
        # save this in order to reproduce our cool network
        np.savetxt("weightsLayer1.txt", self.W1, fmt="%s")
        np.savetxt("weightsLayer2.txt", self.W2, fmt="%s")

    def predictOutput(self):
        print ("Predicted XOR output data based on trained weights: ")
        print ("Expected (X1-X3): \n" + str(xPredicted))
        print ("Output (Y1): \n" + str(self.feedForward(xPredicted)))
        
myNeuralNetwork = Neural_Network()
trainingEpochs = 1000

#trainingEpochs = 1000
for i in range(trainingEpochs): # train myNeuralNetwork 1,000 times
    print ("Epoch # " + str(i) + "\n")
    print ("Network Input : \n" + str(X))
    print ("Expected Output of XOR Gate Neural Network: \n" + str(y))
    print ("Actual Output from XOR Gate Neural Network: \n" + \
           str(myNeuralNetwork.feedForward(X)))
    
    # mean sum squared loss
    Loss = np.mean(np.square(y - myNeuralNetwork.feedForward(X)))
    myNeuralNetwork.saveSumSquaredLossList(i,Loss)
    print ("Sum Squared Loss: \n" + str(Loss))
    print ("\n")
    myNeuralNetwork.trainNetwork(X, y)
    myNeuralNetwork.saveWeights()
    myNeuralNetwork.predictOutput()

Epoch # 0

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.27194742]
 [0.23090458]
 [0.27601219]
 [0.20364533]
 [0.30172087]
 [0.27585401]
 [0.27801169]
 [0.2444376 ]]
Sum Squared Loss: 
0.18954094800253224


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23000385]
Epoch # 1

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.2702567 ]
 [0.23000385]
 [0.27101135]
 [0.20127097]
 [0.29701644]
 [0.27333354]
 [0.27089445]
 [0.24112168]]
Sum Squared Loss: 
0.18894928905646158


Predicted XOR output data based on trained weights: 
E

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.24233592]
Epoch # 26

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.30833198]
 [0.24233592]
 [0.25744918]
 [0.20538035]
 [0.28356688]
 [0.26461724]
 [0.22565508]
 [0.24513697]]
Sum Squared Loss: 
0.17709542268799422


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.24235711]
Epoch # 27

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.31068809]
 [0.24235711]
 [0.25760617]
 [0.20534897]
 [0.28358389]
 [0.26391341]
 [0.22470656

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23831631]
Epoch # 46

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.36818903]
 [0.23831631]
 [0.2611642 ]
 [0.20207128]
 [0.28556556]
 [0.24579204]
 [0.21088448]
 [0.24448991]]
Sum Squared Loss: 
0.16528106071584986


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23788629]
Epoch # 47

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.37187883]
 [0.23788629]
 [0.26128535]
 [0.20182582]
 [0.28567434]
 [0.24462172]
 [0.21034247

 [0.24592002]]
Sum Squared Loss: 
0.15297036490489985


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.22803722]
Epoch # 63

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.43776319]
 [0.22803722]
 [0.26069366]
 [0.19853928]
 [0.28563815]
 [0.2245433 ]
 [0.20338652]
 [0.24621495]]
Sum Squared Loss: 
0.1521321309554966


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.2272445]
Epoch # 64

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.44217846]
 [0.2272445 ]
 [0.26047076]


 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.50430496]
 [0.21451268]
 [0.25494414]
 [0.19930176]
 [0.28130967]
 [0.20734341]
 [0.1986565 ]
 [0.25509783]]
Sum Squared Loss: 
0.13911462942461644


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.21351683]
Epoch # 79

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.50864324]
 [0.21351683]
 [0.25438913]
 [0.19957221]
 [0.2808775 ]
 [0.20637062]
 [0.19836867]
 [0.25602579]]
Sum Squared Loss: 
0.1382365690629832


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.21251358]
Epoch # 80

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.18436518]
Epoch # 107

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.61353465]
 [0.18436518]
 [0.23288333]
 [0.22039653]
 [0.26456871]
 [0.18848797]
 [0.18949646]
 [0.30002389]]
Sum Squared Loss: 
0.1146943796035148


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.18330854]
Epoch # 108

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.6165889 ]
 [0.18330854]
 [0.23196101]
 [0.22156455]
 [0.26390057]
 [0.18807495]
 [0.1890932

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.6728457 ]
 [0.15933233]
 [0.21003125]
 [0.25014158]
 [0.2493497 ]
 [0.17911918]
 [0.1774798 ]
 [0.35563371]]
Sum Squared Loss: 
0.0975083267074215


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15819691]
Epoch # 131

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.67497057]
 [0.15819691]
 [0.20897704]
 [0.25142467]
 [0.24873885]
 [0.17867325]
 [0.17682392]
 [0.35824802]]
Sum Squared Loss: 
0.09680795215066704


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15705725]
Epoch # 132

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12318519]
Epoch # 161

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.72677384]
 [0.12318519]
 [0.17748729]
 [0.27576377]
 [0.23585983]
 [0.16458785]
 [0.153784  ]
 [0.43778168]]
Sum Squared Loss: 
0.07747906272923813


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.1220405]
Epoch # 162

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.72818783]
 [0.1220405 ]
 [0.17651076]
 [0.27590226]
 [0.23561115]
 [0.1641708 ]
 [0.1529556

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10168162]
Epoch # 181

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.75225468]
 [0.10168162]
 [0.16010263]
 [0.26914039]
 [0.23090663]
 [0.15824242]
 [0.13712666]
 [0.49144031]]
Sum Squared Loss: 
0.06569768975342472


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10070019]
Epoch # 182

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.75338645]
 [0.10070019]
 [0.15937049]
 [0.26832661]
 [0.23057452]
 [0.15804775]
 [0.136294

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.08247144]
Epoch # 203

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.774487  ]
 [0.08247144]
 [0.14730121]
 [0.24365492]
 [0.21854   ]
 [0.15609813]
 [0.1190283 ]
 [0.55392255]]
Sum Squared Loss: 
0.05300027566828092


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.08171519]
Epoch # 204

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.77537697]
 [0.08171519]
 [0.14687477]
 [0.24221741]
 [0.21770031]
 [0.15606291]
 [0.118225

0.03700004602120313


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.06218977]
Epoch # 236

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.79973697]
 [0.06218977]
 [0.13745966]
 [0.1943633 ]
 [0.18368237]
 [0.15193737]
 [0.09461878]
 [0.64468182]]
Sum Squared Loss: 
0.036584124456435385


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0617094]
Epoch # 237

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.80039387]
 [0.0617094 ]
 [0.13722793]
 [0.19296984]
 [0.18256625]
 [

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.05272328]
Epoch # 259

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.81371326]
 [0.05272328]
 [0.13186199]
 [0.16573625]
 [0.15997146]
 [0.14319606]
 [0.08097118]
 [0.69527328]]
Sum Squared Loss: 
0.028481158607939136


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.05237876]
Epoch # 260

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.81427366]
 [0.05237876]
 [0.13159642]
 [0.16465664]
 [0.15905251]
 [0.14273932]
 [0.08044

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.04590366]
Epoch # 282

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.82579901]
 [0.04590366]
 [0.12525881]
 [0.14400784]
 [0.14128751]
 [0.1321001 ]
 [0.07022985]
 [0.73457461]]
Sum Squared Loss: 
0.022709577949625012


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.04565312]
Epoch # 283

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.82628941]
 [0.04565312]
 [0.12495304]
 [0.14319628]
 [0.14058409]
 [0.13160815]
 [0.06982

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.04165604]
Epoch # 301

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.83467451]
 [0.04165604]
 [0.11933655]
 [0.13012669]
 [0.12922553]
 [0.12294701]
 [0.06323155]
 [0.76028413]]
Sum Squared Loss: 
0.01918988051711562


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.04145934]
Epoch # 302

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.83511691]
 [0.04145934]
 [0.11902216]
 [0.12947754]
 [0.12866012]
 [0.12248177]
 [0.062903

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.84427585]
 [0.03766803]
 [0.11221176]
 [0.11684929]
 [0.11763772]
 [0.11282722]
 [0.05652908]
 [0.7852667 ]]
Sum Squared Loss: 
0.015973583234245692


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03751703]
Epoch # 325

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.84466726]
 [0.03751703]
 [0.11191029]
 [0.11634168]
 [0.11719357]
 [0.11241655]
 [0.05627391]
 [0.78622773]]
Sum Squared Loss: 
0.015854029416722152


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03736766]
Epoch # 326

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03420986]
Epoch # 350

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.85381032]
 [0.03420986]
 [0.10471739]
 [0.10513139]
 [0.10735136]
 [0.1029585 ]
 [0.05067889]
 [0.80752191]]
Sum Squared Loss: 
0.013287626469165408


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03409389]
Epoch # 351

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.85415167]
 [0.03409389]
 [0.10444478]
 [0.10473508]
 [0.10700195]
 [0.10261159]
 [0.05048

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03208177]
Epoch # 370

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.86031208]
 [0.03208177]
 [0.09949992]
 [0.09782537]
 [0.10088781]
 [0.096444  ]
 [0.04708667]
 [0.82143574]]
Sum Squared Loss: 
0.011699266931256124


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03198501]
Epoch # 371

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.86061993]
 [0.03198501]
 [0.09925202]
 [0.09749152]
 [0.1005912 ]
 [0.09614066]
 [0.04692

[0.03004819]
Epoch # 393

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.86701294]
 [0.03004819]
 [0.09410223]
 [0.09078122]
 [0.09460064]
 [0.08995211]
 [0.04367299]
 [0.8348399 ]]
Sum Squared Loss: 
0.010238845442182164


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02996803]
Epoch # 394

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.86728715]
 [0.02996803]
 [0.09388157]
 [0.09050242]
 [0.09435044]
 [0.08969149]
 [0.04353895]
 [0.83536976]]
Sum Squared Loss: 
0.010182568489192976


Predicted XOR output data based on 

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.87372514]
 [0.0281475 ]
 [0.08871664]
 [0.0841507 ]
 [0.08861683]
 [0.08368868]
 [0.04050747]
 [0.84742061]]
Sum Squared Loss: 
0.008933458635562306


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02808129]
Epoch # 420

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.87396692]
 [0.02808129]
 [0.08852343]
 [0.08391906]
 [0.08840642]
 [0.08346758]
 [0.04039771]
 [0.84785921]]
Sum Squared Loss: 
0.008889128424143945


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02801554]
Epoch # 421

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02645176]
Epoch # 447

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.88008754]
 [0.02645176]
 [0.083657  ]
 [0.07820747]
 [0.08318551]
 [0.07797458]
 [0.03770907]
 [0.85864908]]
Sum Squared Loss: 
0.007824439359429239


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0263967]
Epoch # 448

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.88030005]
 [0.0263967 ]
 [0.08348896]
 [0.0780142 ]
 [0.08300767]
 [0.07778742]
 [0.037618

 [0.86773536]]
Sum Squared Loss: 
0.006967529163763065


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02502906]
Epoch # 475

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.88569774]
 [0.02502906]
 [0.07924451]
 [0.07321049]
 [0.07856027]
 [0.07311246]
 [0.03538296]
 [0.86804444]]
Sum Squared Loss: 
0.0069390375749974675


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02498243]
Epoch # 476

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.88588581]
 [0.02498243]
 [0.079

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.89183718]
 [0.02353862]
 [0.07447599]
 [0.06797582]
 [0.07364923]
 [0.06797454]
 [0.03296952]
 [0.87783491]]
Sum Squared Loss: 
0.006059586738714231


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02349992]
Epoch # 511

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.89200011]
 [0.02349992]
 [0.07435034]
 [0.06784   ]
 [0.07352083]
 [0.06784072]
 [0.03290718]
 [0.87808819]]
Sum Squared Loss: 
0.006037438468678165


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0234614]
Epoch # 512

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]

Actual Output from XOR Gate Neural Network: 
[[0.8960215 ]
 [0.02255733]
 [0.07126424]
 [0.06453556]
 [0.07038113]
 [0.06457803]
 [0.03139452]
 [0.88423773]]
Sum Squared Loss: 
0.005509266848942023


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02252335]
Epoch # 538

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.89616835]
 [0.02252335]
 [0.0711521 ]
 [0.0644166 ]
 [0.07026751]
 [0.06446034]
 [0.03134019]
 [0.88445867]]
Sum Squared Loss: 
0.005490637380343622


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02248953]
Epoch # 539

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neur

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02166171]
Epoch # 565

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.89993531]
 [0.02166171]
 [0.06828882]
 [0.06140404]
 [0.06737611]
 [0.06147524]
 [0.0299672 ]
 [0.89004294]]
Sum Squared Loss: 
0.005027915523200549


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02163172]
Epoch # 566

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90006789]
 [0.02163172]
 [0.06818851]
 [0.06129936]
 [0.06727514]
 [0.06137136]
 [0.02991

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90359841]
 [0.0208409 ]
 [0.06552918]
 [0.05854415]
 [0.06460509]
 [0.05863386]
 [0.02866793]
 [0.89532489]]
Sum Squared Loss: 
0.0046049471829065075


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02081429]
Epoch # 595

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90371835]
 [0.02081429]
 [0.06543924]
 [0.05845162]
 [0.064515  ]
 [0.05854183]
 [0.02862595]
 [0.89549545]]
Sum Squared Loss: 
0.004591531691816433


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02078778]
Epoch # 596

Network Input : 
[[0. 0. 0.]
 [0. 0. 1

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02003839]
Epoch # 626

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90724685]
 [0.02003839]
 [0.06280464]
 [0.05576013]
 [0.0618819 ]
 [0.05586193]
 [0.02740606]
 [0.90044825]]
Sum Squared Loss: 
0.004208733165990842


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02001484]
Epoch # 627

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90735489]
 [0.02001484]
 [0.06272432]
 [0.05567863]
 [0.06180178]
 [0.05578071]
 [0.02736

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91034595]
 [0.01936731]
 [0.06050893]
 [0.05344328]
 [0.0595955 ]
 [0.05355138]
 [0.02635743]
 [0.90469788]]
Sum Squared Loss: 
0.0038908796924063157


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01934613]
Epoch # 657

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91044443]
 [0.01934613]
 [0.06043626]
 [0.05337036]
 [0.05952323]
 [0.05347861]
 [0.02632444]
 [0.90483143]]
Sum Squared Loss: 
0.0038810521977254374


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01932503]
Epoch # 658

Network Input : 
[[0. 0. 0.]
 [0. 0. 

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01870457]
Epoch # 689

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91344698]
 [0.01870457]
 [0.05822862]
 [0.05116707]
 [0.05733068]
 [0.05127855]
 [0.02532788]
 [0.9088605 ]]
Sum Squared Loss: 
0.003589266712611068


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01868558]
Epoch # 690

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.9135364 ]
 [0.01868558]
 [0.05816311]
 [0.05110205]
 [0.0572657 ]
 [0.05121358]
 [0.02529

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01812541]
Epoch # 721

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91618783]
 [0.01812541]
 [0.05622692]
 [0.04918887]
 [0.05534697]
 [0.04930134]
 [0.02443319]
 [0.91246812]]
Sum Squared Loss: 
0.003335842844738854


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0181082]
Epoch # 722

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91626965]
 [0.0181082 ]
 [0.05616736]
 [0.04913028]
 [0.055288  ]
 [0.04924275]
 [0.024406

Sum Squared Loss: 
0.0031533839375910973


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01767825]
Epoch # 748

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91832238]
 [0.01767825]
 [0.05467679]
 [0.04766933]
 [0.05381321]
 [0.0477815 ]
 [0.02374571]
 [0.91523296]]
Sum Squared Loss: 
0.0031467392206576718


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01766234]
Epoch # 749

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91839857]
 [0.01766234]
 [0.0546216 ]
 [0.047

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91980959]
 [0.01736855]
 [0.05360122]
 [0.04662122]
 [0.05275013]
 [0.04673272]
 [0.02327128]
 [0.91713685]]
Sum Squared Loss: 
0.003019146838600187


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01735351]
Epoch # 769

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91988199]
 [0.01735351]
 [0.05354896]
 [0.04657042]
 [0.05269849]
 [0.04668188]
 [0.02324828]
 [0.91722906]]
Sum Squared Loss: 
0.003013021634288044


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01733851]
Epoch # 770

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.

0.0028395325682577027


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01690678]
Epoch # 800

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92203971]
 [0.01690678]
 [0.05199516]
 [0.04506547]
 [0.05116422]
 [0.04517533]
 [0.02256655]
 [0.9199581 ]]
Sum Squared Loss: 
0.0028340727694294134


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01689297]
Epoch # 801

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92210664]
 [0.01689297]
 [0.05194708]
 [0.04501907]
 [0.05111678

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92385511]
 [0.01653304]
 [0.05069366]
 [0.04381279]
 [0.04988027]
 [0.04392084]
 [0.02199852]
 [0.92222565]]
Sum Squared Loss: 
0.0026888324108851613


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01652017]
Epoch # 829

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92391778]
 [0.01652017]
 [0.05064883]
 [0.04376977]
 [0.04983606]
 [0.04387775]
 [0.021979  ]
 [0.92230346]]
Sum Squared Loss: 
0.002683904280112958


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01650733]
Epoch # 830

Network Input : 
[[0. 0. 0.]
 [0. 0. 1

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01618428]
Epoch # 856

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92555695]
 [0.01618428]
 [0.04947832]
 [0.04264943]
 [0.04868217]
 [0.04275545]
 [0.02147041]
 [0.92432826]]
Sum Squared Loss: 
0.00255699353210272


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01617225]
Epoch # 857

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92561577]
 [0.01617225]
 [0.04943639]
 [0.04260941]
 [0.04864086]
 [0.04271535]
 [0.021452

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01583531]
Epoch # 886

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92726677]
 [0.01583531]
 [0.04826181]
 [0.04149106]
 [0.04748369]
 [0.04159475]
 [0.02094389]
 [0.92641878]]
Sum Squared Loss: 
0.0024286569799942836


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01582409]
Epoch # 887

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92732188]
 [0.01582409]
 [0.04822268]
 [0.04145389]
 [0.04744515]
 [0.04155751]
 [0.0209

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0155197]
Epoch # 915

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.9288187 ]
 [0.0155197 ]
 [0.04716153]
 [0.04044854]
 [0.0464003 ]
 [0.04054993]
 [0.02046937]
 [0.9282976 ]]
Sum Squared Loss: 
0.0023156809482911193


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01550917]
Epoch # 916

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92887056]
 [0.01550917]
 [0.04712482]
 [0.04041385]
 [0.04636416]
 [0.04051515]
 [0.02045

Actual Output from XOR Gate Neural Network: 
[[0.9303785 ]
 [0.01520347]
 [0.04605932]
 [0.03940909]
 [0.04531551]
 [0.03950797]
 [0.01999555]
 [0.93016847]]
Sum Squared Loss: 
0.0022054344227828444


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01519361]
Epoch # 947

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93042723]
 [0.01519361]
 [0.04602495]
 [0.03937675]
 [0.04528169]
 [0.03947556]
 [0.0199808 ]
 [0.93022663]]
Sum Squared Loss: 
0.0022020435218326915


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01518376]
Epoch # 948

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Ne

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01489761]
Epoch # 978

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93189136]
 [0.01489761]
 [0.04499375]
 [0.03840877]
 [0.04426722]
 [0.0385051 ]
 [0.01953884]
 [0.93196662]]
Sum Squared Loss: 
0.0021016166356708265


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.01488836]
Epoch # 979

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93193715]
 [0.01488836]
 [0.04496155]
 [0.03837862]
 [0.04423555]
 [0.03847486]
 [0.0195